#!/bin/bash/

#### Special Vara #####
echo "All Variables passed to script: $@"
echo "number of variables passed: $#"
echo "First variable:$1"
echo "script name: $0"
echo "Who is running this: $USER"
echo "Which directory: $PWD"
echo "Home Directory: $HOME"