#!/bin/bash/

#### Special Vara #####
echo "All Variables passed to script: $@"
echo "number of variables passed: $#"
echo "First variable:$1"
echo "script name: $0"
echo "Who is running this: $USER"
echo "Which directory: $PWD"
echo "Home Directory: $HOME"
echo "PID of the current script: $$"
sleep 5 &
echo "PID of the background command rinning just now: $!"
wait $!
echo "Line number: $LINENO"
echo "script executed in $SECONDS seconds"
echo "Randome number: $RANDOM"
echo "Exit code of Privious command: $?"


