#!/bin/bash

NUM1=10
NUM2=30

SUM=$(($NUM1+$NUM2))

echo "Sum is: $SUM"


#Arrar
MOVIES=("RRR" "Varanasi" "Pushpa") # index always starts from 0
echo "Movies are ${MoVIES[@]}"
echo "First Movie is ${MoVIES[0]}"
echo "First Movie is ${MoVIES[1]}"
echo "First Movie is ${MoVIES[2]}"
