#!/bin/bash/

USERID=$(id -u)

#check root access or not
if [ $USERID -ne 0]; then
     echo "Please run this script with root access"
     exit 1
     
fi

echo "Installing MySQL"
dnf install mysqldfsd -y

echo "I am continuing..."

echo " I am still continuing"

#fi [$? -ne 0]; then
#echo "mysql is installed"
